version: '3.1'

services:
  app:
    image: spring-lab4:latest
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - DB_IP=postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - JPA_HIBERNATE_DDL_AUTO=validate
    networks:
      - spring-network

  postgres:
    container_name: postgresql
    image: postgres:14
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge